### ISSUE TITLE
dev-node/app-builder-bin-3.4.2_p2020121: fails due to lack of .tgz files.

### ISSUE THREAD

**Issue by parona-source** [Alessandro-Barbieri/node-overlay#7]
node.eclass cant handle an ebuild without .tgz files in DISTDIR and will fail.

Relevant error:
```
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /var/tmp/portage/dev-node/app-builder-bin-3.4.2_p20201214/distdir/*.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/var/tmp/portage/dev-node/app-builder-bin-3.4.2_p20201214/distdir/*.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Line 149-152 from node.eclass in function node_src_compile:
```bash
    for file in "${DISTDIR}"/*.tgz; do
        "${NPM}" cache add "${file}" || die
        addfile "${file}" || die
    done
```

This can be worked around with first checking if the files exists.

```bash
    # Check that files exists before
    if ls "${DISTDIR}"/*.tgz &> /dev/null; then
        for file in "${DISTDIR}"/*.tgz; do
            "${NPM}" cache add "${file}" || die
            addfile "${file}" || die
        done
    fi
```

[Full build.log](https://dpaste.com/99ADTSQLQ)
[npm debug log](https://dpaste.com/DYZCQRPJW)

**Comment by Alessandro-Barbieri** [comment]
thanks, I'll get a look

**Comment by Alessandro-Barbieri** [comment]
Try again and let me know

**Comment by parona-source** [comment]
This should work as I used the same change in my fork and that went through fine. I'll sync my fork and try to get to zulip-desktop again and see what fails on the way. iirc zulip-desktop had some issues with electron versions and not actually building the client, and when adding building to the ebuild it was missing required dependencies. but ill probably elaborate on that in a different issue when ive got to it

**Comment by Alessandro-Barbieri** [comment]
okok
